services:
  - type: web
    name: sunsy-music-bot
    env: python
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
